User.create!([
  {username: "charles_bukowski", password_digest: "$2a$10$XmpHL0c1Dt9mWvmKYRcRFOcMZ0aZ0rTWounjVRlA87E1q228/M1qy", session_token: "DpNlPn-MeniJIYpxzjJVzg", filepicker_url: "https://www.filepicker.io/api/file/Udy9s0mITZelFtL9XABc"},
  {username: "sylvia_plath", password_digest: "$2a$10$A2.sGWGFOLKsEWCuc5Pwge4r5ZgQja6YMQWDR8466POJ3mNFHT78i", session_token: "Z2LjDfKokMtZykTzatstmw", filepicker_url: "https://www.filepicker.io/api/file/l06hExojQRqNi0x6Ak8v"},
  {username: "allen_ginsberg", password_digest: "$2a$10$QvebnyZfIhNX.N4N1iWm7OpKvmRRW9VKAP7KQRui0Gxu1tPJhronC", session_token: "B_csFNukk8_G_2fvqJ-4wA", filepicker_url: "https://www.filepicker.io/api/file/i5IYAzUcTHSwQDEQ8foW"},
  {username: "Guest", password_digest: "$2a$10$Lp/vKzjASrk1Wt2BlvQQduCKxCQJgDUuzpcdabKh8Yq4tfyhJ2TYW", session_token: "IP0dOjrAW7RlM5qBY5Q5lw", filepicker_url: "https://www.filepicker.io/api/file/pHF0SBJoRWS1fJVQmTHA"},
  {username: "gil_scott_heron", password_digest: "$2a$10$FmqgeuLOekITTE3O7kWM5eZTmiQ4je.CpgW8SLtakjHOO7rYkn7.O", session_token: "vzsLsIG_0yViwxy0ayVQNw", filepicker_url: "https://www.filepicker.io/api/file/qwbuoD4R3av0ubKmbDXw"},
  {username: "ee_cummings", password_digest: "$2a$10$jHyOxVdpdSwQd9xAmL5Gyuz9cb/V5p8RlO3mANR7A7qUfWHfZfjT6", session_token: "hlBW2bOwM0ttZJtN6FnWqA", filepicker_url: "https://www.filepicker.io/api/file/dfOyzJtuQmewB57kDwhP"}
])
Comment.create!([
  {user_id: 3, text_id: 11, content: "i found this hard to read"},
  {user_id: 1, text_id: 1, content: "i was drunk when i wrote this."}
])
Critique.create!([
  {user_id: 6, text_id: 3, content: "interesting way to start it off. have you considered using more punctuation marks?", start_idx: 0, end_idx: 2},
  {user_id: 1, text_id: 3, content: "i like getting drunk.", start_idx: 340, end_idx: 348},
  {user_id: 2, text_id: 2, content: "how whimsical", start_idx: 492, end_idx: 532},
  {user_id: 6, text_id: 2, content: "great rhythm to the way these lines are broken up", start_idx: 882, end_idx: 923},
  {user_id: 3, text_id: 3, content: "i like the imagery, but is there a better way to put this than \"puppet-people\"?", start_idx: 270, end_idx: 294},
])
Text.create!([
  {title: "the tragedy of the leaves", content: "I awakened to dryness and the ferns were dead,\nthe potted plants yellow as corn;\nmy woman was gone\nand the empty bottles like bled corpses\nsurrounded me with their uselessness;\nthe sun was still good, though,\nand my landlady’s note cracked in fine and\nundemanding yellowness; what was needed now\nwas a good comedian, ancient style, a jester\nwith jokes upon absurd pain; pain is absurd\nbecause it exists, nothing more;\nI shaved carefully with an old razor\nthe man who had once been young and\nsaid to have genius; but\nthat’s the tragedy of the leaves,\nthe dead ferns, the dead plants;\nand I walked into a dark hall\nwhere the landlady stood\nexecrating and final,\nsending me to hell,\nwaving her fat, sweaty arms\nand screaming\nscreaming for rent\nbecause the world has failed us\nboth", user_id: 1},
  {title: "bluebird", content: "there's a bluebird in my heart that\nwants to get out\nbut I'm too tough for him,\nI say, stay in there, I'm not going\nto let anybody see\nyou.\nthere's a bluebird in my heart that\nwants to get out\nbut I pour whiskey on him and inhale\ncigarette smoke\nand the whores and the bartenders\nand the grocery clerks\nnever know that\nhe's\nin there.\n\nthere's a bluebird in my heart that\nwants to get out\nbut I'm too tough for him,\nI say,\nstay down, do you want to mess\nme up?\nyou want to screw up the\nworks?\nyou want to blow my book sales in\nEurope?\nthere's a bluebird in my heart that\nwants to get out\nbut I'm too clever, I only let him out\nat night sometimes\nwhen everybody's asleep.\nI say, I know that you're there,\nso don't be\nsad.\nthen I put him back,\nbut he's singing a little\nin there, I haven't quite let him\ndie\nand we sleep together like\nthat\nwith our\nsecret pact\nand it's nice enough to\nmake a man\nweep, but I don't\nweep, do\nyou?", user_id: 1},
  {title: "Soliloquy Of The Solipsist", content: "I?\nI walk alone;\nThe midnight street\nSpins itself from under my feet;\nWhen my eyes shut\nThese dreaming houses all snuff out;\nThrough a whim of mine\nOver gables the moon's celestial onion\nHangs high.\n\nI\nMake houses shrink\nAnd trees diminish\nBy going far; my look's leash\nDangles the puppet-people\nWho, unaware how they dwindle,\nLaugh, kiss, get drunk,\nNor guess that if I choose to blink\nThey die.\n\nI\nWhen in good humor,\nGive grass its green\nBlazon sky blue, and endow the sun\nWith gold;\nYet, in my wintriest moods, I hold\nAbsolute power\nTo boycott any color and forbid any flower\nTo be.\n\nI\nKnow you appear\nVivid at my side,\nDenying you sprang out of my head,\nClaiming you feel\nLove fiery enough to prove flesh real,\nThough it's quite clear\nAll your beauty, all your wit, is a gift, my dear,\nFrom me.", user_id: 2},
  {title: "A Supermarket in California", content: "          What thoughts I have of you tonight, Walt Whitman, for\nI walked down the sidestreets under the trees with a headache\nself-conscious looking at the full moon.\n          In my hungry fatigue, and shopping for images, I went\ninto the neon fruit supermarket, dreaming of your enumerations!\n          What peaches and what penumbras!  Whole families\nshopping at night!  Aisles full of husbands!  Wives in the\navocados, babies in the tomatoes!--and you, Garcia Lorca, what\nwere you doing down by the watermelons?\n\n          I saw you, Walt Whitman, childless, lonely old grubber,\npoking among the meats in the refrigerator and eyeing the grocery\nboys.\n          I heard you asking questions of each: Who killed the\npork chops?  What price bananas?  Are you my Angel?\n          I wandered in and out of the brilliant stacks of cans\nfollowing you, and followed in my imagination by the store\ndetective.\n          We strode down the open corridors together in our\nsolitary fancy tasting artichokes, possessing every frozen\ndelicacy, and never passing the cashier.\n\n          Where are we going, Walt Whitman?  The doors close in\nan hour.  Which way does your beard point tonight?\n          (I touch your book and dream of our odyssey in the\nsupermarket and feel absurd.)\n          Will we walk all night through solitary streets?  The\ntrees add shade to shade, lights out in the houses, we'll both be\nlonely.\n\n          Will we stroll dreaming of the lost America of love\npast blue automobiles in driveways, home to our silent cottage?\n          Ah, dear father, graybeard, lonely old courage-teacher,\nwhat America did you have when Charon quit poling his ferry and\nyou got out on a smoking bank and stood watching the boat\ndisappear on the black waters of Lethe?", user_id: 3},
  {title: "Mirror", content: "I am silver and exact. I have no preconceptions.\nWhatever I see I swallow immediately\nJust as it is, unmisted by love or dislike.\nI am not cruel, only truthful‚\nThe eye of a little god, four-cornered.\nMost of the time I meditate on the opposite wall.\nIt is pink, with speckles. I have looked at it so long\nI think it is part of my heart. But it flickers.\nFaces and darkness separate us over and over.\n\nNow I am a lake. A woman bends over me,\nSearching my reaches for what she really is.\nThen she turns to those liars, the candles or the moon.\nI see her back, and reflect it faithfully.\nShe rewards me with tears and an agitation of hands.\nI am important to her. She comes and goes.\nEach morning it is her face that replaces the darkness.\nIn me she has drowned a young girl, and in me an old woman\nRises toward her day after day, like a terrible fish.", user_id: 2},
  {title: "Lady Lazarus", content: "I have done it again.\nOne year in every ten\nI manage it--\n\nA sort of walking miracle, my skin\nBright as a Nazi lampshade,\nMy right foot\n\nA paperweight,\nMy face a featureless, fine\nJew linen.\n\nPeel off the napkin\nO my enemy.\nDo I terrify?--\n\nThe nose, the eye pits, the full set of teeth?\nThe sour breath\nWill vanish in a day.\n\nSoon, soon the flesh\nThe grave cave ate will be\nAt home on me\n\nAnd I a smiling woman.\nI am only thirty.\nAnd like the cat I have nine times to die.\n\nThis is Number Three.\nWhat a trash\nTo annihilate each decade.\n\nWhat a million filaments.\nThe peanut-crunching crowd\nShoves in to see\n\nThem unwrap me hand and foot--\nThe big strip tease.\nGentlemen, ladies\n\nThese are my hands\nMy knees.\nI may be skin and bone,\n\nNevertheless, I am the same, identical woman.\nThe first time it happened I was ten.\nIt was an accident.\n\nThe second time I meant\nTo last it out and not come back at all.\nI rocked shut\n\nAs a seashell.\nThey had to call and call\nAnd pick the worms off me like sticky pearls.\n\nDying\nIs an art, like everything else.\nI do it exceptionally well.\n\nI do it so it feels like hell.\nI do it so it feels real.\nI guess you could say I’ve a call.\n\nIt’s easy enough to do it in a cell.\nIt’s easy enough to do it and stay put.\nIt’s the theatrical\n\nComeback in broad day\nTo the same place, the same face, the same brute\nAmused shout:\n\n‘A miracle!'\nThat knocks me out.\nThere is a charge\n\nFor the eyeing of my scars, there is a charge\nFor the hearing of my heart--\nIt really goes.\n\nAnd there is a charge, a very large charge\nFor a word or a touch\nOr a bit of blood\n\nOr a piece of my hair or my clothes.\nSo, so, Herr Doktor.\nSo, Herr Enemy.\n\nI am your opus,\nI am your valuable,\nThe pure gold baby\n\nThat melts to a shriek.\nI turn and burn.\nDo not think I underestimate your great concern.\n\nAsh, ash--\nYou poke and stir.\nFlesh, bone, there is nothing there--\n\nA cake of soap, \nA wedding ring,\nA gold filling.\n\nHerr God, Herr Lucifer\nBeware\nBeware.\n\nOut of the ash\nI rise with my red hair\nAnd I eat men like air.", user_id: 2},
  {title: "The Revolution Will Not Be Televised", content: "You will not be able to stay home, brother.\nYou will not be able to plug in, turn on and cop out.\nYou will not be able to lose yourself on skag and\nskip out for beer during commercials,\nBecause the revolution will not be televised.\n\nThe revolution will not be televised.\nThe revolution will not be brought to you by Xerox\nIn 4 parts without commercial interruptions.\nThe revolution will not show you pictures of Nixon\nblowing a bugle and leading a charge by John\nMitchell, General Abrams and Mendel Rivers to eat\nhog maws confiscated from a Harlem sanctuary.\n\nThe revolution will not be televised.\nThe revolution will not be brought to you by the\nSchaefer Award Theatre and will not star Natalie\nWoods and Steve McQueen or Bullwinkle and Julia.\nThe revolution will not give your mouth sex appeal.\nThe revolution will not get rid of the nubs.\nThe revolution will not make you look five pounds\nthinner, the revolution will not be televised, Brother.\n\nThere will be no pictures of you and Willie Mays\npushing that shopping cart down the block on the dead run,\nor trying to slide that color television into a stolen ambulance.\nNBC will not be able predict the winner at 8:32\non reports from 29 districts.\nThe revolution will not be televised.\n\nThere will be no pictures of pigs shooting down\nbrothers in the instant replay.\nThere will be no pictures of Whitney Young being\nrun out of Harlem on a rail with a brand new process.\nThere will be no slow motion or still life of Roy\nWilkens strolling through Watts in a Red, Black and\nGreen liberation jumpsuit that he had been saving\nFor just the right occasion.\n\nGreen Acres, The Beverly Hillbillies, and Hooterville\nJunction will no longer be so god damned relevant, and\nwomen will not care if Dick finally screwed\nJane on Search for Tomorrow because Black people\nwill be in the street looking for a brighter day.\nThe revolution will not be televised.\n\nThere will be no highlights on the eleven o'clock\nnews and no pictures of hairy armed women\nliberationists and Jackie Onassis blowing her nose.\nThe theme song will not be written by Jim Webb or\nFrancis Scott Key, nor sung by Glen Campbell, Tom\nJones, Johnny Cash or Englebert Humperdink.\nThe revolution will not be televised.\n\nThe revolution will not be right back\nafter a message about a white tornado, white lightning, or white people.\nYou will not have to worry about a dove in your\nbedroom, a tiger in your tank, or the giant in your toilet bowl.\nThe revolution will not go better with Coke.\nThe revolution will not fight the germs that may cause bad breath.\nThe revolution will put you in the driver's seat.\n\nThe revolution will not be televised, will not be televised,\nwill not be televised, will not be televised.\nThe revolution will be no re-run brothers;\nThe revolution will be live.", user_id: 5},
  {title: "i carry your heart with me(i carry it in", content: "i carry your heart with me(i carry it in\nmy heart)i am never without it(anywhere\ni go you go,my dear;and whatever is done\nby only me is your doing,my darling)\n                             i fear\nno fate(for you are my fate,my sweet)i want\nno world(for beautiful you are my world,my true)\nand it’s you are whatever a moon has always meant\nand whatever a sun will always sing is you\n\nhere is the deepest secret nobody knows\n(here is the root of the root and the bud of the bud\nand the sky of the sky of a tree called life;which grows\nhigher than soul can hope or mind can hide)\nand this is the wonder that's keeping the stars apart\n\ni carry your heart(i carry it in my heart)", user_id: 6},
  {title: "o sweet spontaneous", content: "O sweet spontaneous\nearth how often have\nthe\ndoting\n\n       fingers of\nprurient philosophers pinched\nand\n\npoked\nthee\n, has the naughty thumb\nof science prodded\nthy\n\n    beauty             how\noften have religions taken\nthee upon their scraggy knees\nsqueezing and\n\nbuffeting thee that thou mightest conceive\ngods\n    (but\ntrue\n\nto the incomparable\ncouch of death thy\nrhythmic\nlover\n\n     thou answerest\n\nthem only with\n\n               spring)", user_id: 6},
  {title: "dying is fine)but death", content: "dying is fine)but Death\n\n?o\nbaby\ni\n\nwouldn’t like\n\nDeath if Death\nwere\ngood:for\n\nwhen(instead of stopping to think)you\n\nbegin to feel of it,dying\n’s miraculous\nwhy?be\n\ncause dying is\n\nperfectly natural;perfectly\nputting\nit mildly lively(but\n\nDeath\n\nis strictly\nscientific\n& artificial &\n\nevil & legal)\n\nwe thank thee\ngod\nalmighty for dying\n(forgive us,o life!the sin of Death", user_id: 6},
  {title: "the sky was", content: "the\n   sky\n       was\ncan  dy  lu\nminous\n     edible\nspry\n     pinks shy\nlemons\ngreens  coo  l choc\nolate\ns.\n  un  der,\n  a  lo\nco\nmo\n  tive   s   pout \n                 ing\n                    vi\n                    o\n                    lets", user_id: 6}
])

