# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
u1 = User.create(username: 'charles_bukowski', password: 'password')
u2 = User.create(username: 'sylvia_plath', password: 'password')
u3 = User.create(username: 'allen_ginsberg', password: 'password')

t1 = u1.texts.create(title:'the tragedy of the leaves', 
                    content:"I awakened to dryness and the ferns were dead,\nthe potted plants yellow as corn;\nmy woman was gone\nand the empty bottles like bled corpses\nsurrounded me with their uselessness;\nthe sun was still good, though,\nand my landlady’s note cracked in fine and\nundemanding yellowness; what was needed now\nwas a good comedian, ancient style, a jester\nwith jokes upon absurd pain; pain is absurd\nbecause it exists, nothing more;\nI shaved carefully with an old razor\nthe man who had once been young and\nsaid to have genius; but\nthat’s the tragedy of the leaves,\nthe dead ferns, the dead plants;\nand I walked into a dark hall\nwhere the landlady stood\nexecrating and final,\nsending me to hell,\nwaving her fat, sweaty arms\nand screaming\nscreaming for rent\nbecause the world has failed us\nboth", 
                    created_at:"1960-06-15 01:01:01")
t2 = u1.texts.create(title:'bluebird', 
                    content:"there's a bluebird in my heart that\nwants to get out\nbut I'm too tough for him,\nI say, stay in there, I'm not going\nto let anybody see\nyou.\nthere's a bluebird in my heart that\nwants to get out\nbut I pour whiskey on him and inhale\ncigarette smoke\nand the whores and the bartenders\nand the grocery clerks\nnever know that\nhe's\nin there.\n\nthere's a bluebird in my heart that\nwants to get out\nbut I'm too tough for him,\nI say,\nstay down, do you want to mess\nme up?\nyou want to screw up the\nworks?\nyou want to blow my book sales in\nEurope?\nthere's a bluebird in my heart that\nwants to get out\nbut I'm too clever, I only let him out\nat night sometimes\nwhen everybody's asleep.\nI say, I know that you're there,\nso don't be\nsad.\nthen I put him back,\nbut he's singing a little\nin there, I haven't quite let him\ndie\nand we sleep together like\nthat\nwith our\nsecret pact\nand it's nice enough to\nmake a man\nweep, but I don't\nweep, do\nyou?",
                    created_at:"1975-05-07 01:01:01")
t3 = u2.texts.create(title:'Soliloquy Of The Solipsist', 
                    content:"I?\nI walk alone;\nThe midnight street\nSpins itself from under my feet;\nWhen my eyes shut\nThese dreaming houses all snuff out;\nThrough a whim of mine\nOver gables the moon's celestial onion\nHangs high.\n\nI\nMake houses shrink\nAnd trees diminish\nBy going far; my look's leash\nDangles the puppet-people\nWho, unaware how they dwindle,\nLaugh, kiss, get drunk,\nNor guess that if I choose to blink\nThey die.\n\nI\nWhen in good humor,\nGive grass its green\nBlazon sky blue, and endow the sun\nWith gold;\nYet, in my wintriest moods, I hold\nAbsolute power\nTo boycott any color and forbid any flower\nTo be.\n\nI\nKnow you appear\nVivid at my side,\nDenying you sprang out of my head,\nClaiming you feel\nLove fiery enough to prove flesh real,\nThough it's quite clear\nAll you beauty, all your wit, is a gift, my dear,\nFrom me.",
                    created_at:)
t4 = u3.texts.create(title:'A Supermarket in California', 
                      content:"What thoughts I have of you tonight, Walt Whitman, for I walked down the sidestreets under the trees with a headache self-conscious looking at the full moon.\nIn my hungry fatigue, and shopping for images, I went into the neon fruit supermarket, dreaming of your enumerations!\nWhat peaches and what penumbras!  Whole families shopping at night!  Aisles full of husbands!  Wives in the avocados, babies in the tomatoes!--and you, Garcia Lorca, what were you doing down by the watermelons?\n\nI saw you, Walt Whitman, childless, lonely old grubber, poking among the meats in the refrigerator and eyeing the grocery boys.\nI heard you asking questions of each: Who killed the pork chops?  What price bananas?  Are you my Angel?\nI wandered in and out of the brilliant stacks of cans following you, and followed in my imagination by the store detective.\nWe strode down the open corridors together in our solitary fancy tasting artichokes, possessing every frozen delicacy, and never passing the cashier.\n\nWhere are we going, Walt Whitman?  The doors close in an hour.  Which way does your beard point tonight?\n(I touch your book and dream of our odyssey in the supermarket and feel absurd.)\nWill we walk all night through solitary streets?  The trees add shade to shade, lights out in the houses, we'll both be lonely.\n\nWill we stroll dreaming of the lost America of love past blue automobiles in driveways, home to our silent cottage?\nAh, dear father, graybeard, lonely old courage-teacher, what America did you have when Charon quit poling his ferry and you got out on a smoking bank and stood watching the boat disappear on the black waters of Lethe?",
                      created_at:"1956-05-06 01:01:01")
